log4j.rootLogger=info, R
log4j.appender.R=org.apache.log4j.RollingFileAppender
log4j.appender.R.File=${mlcmd.logfile}
log4j.appender.R.MaxFileSize=100KB
# Keep one backup file
log4j.appender.R.MaxBackupIndex=1
log4j.appender.R.layout=org.apache.log4j.PatternLayout
# same as defaulit
log4j.appender.R.layout.ConversionPattern="%d %-5r %-5p [%t] %c{2} - %m%n

# trace logger
log4j.logger.mlcmd.trace=ALL, T
log4j.appender.T=org.apache.log4j.FileAppender
log4j.appender.T.layout=org.apache.log4j.PatternLayout
log4j.appender.T.File=${mlcmd.tracefile}
# same as defaulit
log4j.appender.T.layout.ConversionPattern="%d %-5r %-5p [%t] %c{2} - %m%n
